import type {Metadata} from "next";
import {ClerkProvider} from "@clerk/nextjs";
import {Inter} from "next/font/google";
import {Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/toaster";
import {ThemeProvider} from "@/providers/theme-provider";

const inter = Inter({subsets: ["latin"]});
const jakarta = Plus_Jakarta_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className={jakarta.className}>
            <ThemeProvider>
                {children}
                <Toaster/>
            </ThemeProvider>
            </body>
            </html>
        </ClerkProvider>
    );
}
